# Generated by Django 5.1 on 2024-08-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
